import pytest
from rdkit import Chem

from gufe import LigandAtomMapper, LigandAtomMapping, SmallMoleculeComponent

from .test_tokenization import GufeTokenizableTestsMixin


def mol_from_smiles(smiles: str) -> Chem.Mol:
    m = Chem.MolFromSmiles(smiles)
    Chem.AllChem.Compute2DCoords(m)  # type: ignore[attr-defined]

    return m


@pytest.fixture(scope="session")
def simple_mapping() -> LigandAtomMapping:
    """Disappearing oxygen on end

    C C O

    C C
    """
    molA = SmallMoleculeComponent(mol_from_smiles("CCO"))
    molB = SmallMoleculeComponent(mol_from_smiles("CC"))

    m = LigandAtomMapping(molA, molB, componentA_to_componentB={0: 0, 1: 1})

    return m


@pytest.fixture(scope="session")
def other_mapping() -> LigandAtomMapping:
    """Disappearing middle carbon

    C C O

    C   C
    """
    molA = SmallMoleculeComponent(mol_from_smiles("CCO"))
    molB = SmallMoleculeComponent(mol_from_smiles("CC"))

    m = LigandAtomMapping(molA, molB, componentA_to_componentB={0: 0, 2: 1})

    return m


class ExampleLigandAtomMapper(LigandAtomMapper):
    def __init__(self, mappings):
        self.mappings = mappings

    @classmethod
    def _defaults(cls):
        return {}

    def _to_dict(self):
        return {"mappings": self.mappings}

    @classmethod
    def _from_dict(cls, dct):
        return cls(**dct)

    def _mappings_generator(self, componentA, componentB):
        for mapping in self.mappings:
            yield mapping.componentA_to_componentB


class TestLigandAtomMapper(GufeTokenizableTestsMixin):
    cls = ExampleLigandAtomMapper
    repr = None

    @pytest.fixture
    def instance(self, simple_mapping, other_mapping):
        return ExampleLigandAtomMapper([simple_mapping, other_mapping])

    def test_abstract_error(self):
        # make sure users cannot use LigandAtomMapper directly
        with pytest.raises(TypeError):
            LigandAtomMapper()

    def test_suggest_mappings(self, instance, simple_mapping, other_mapping):
        # a correctly implemented ligand atom mapping should return the
        # mappings generated by the _mappings_generator
        molA = simple_mapping.componentA
        molB = simple_mapping.componentB

        results = list(instance.suggest_mappings(molA, molB))
        assert len(results) == 2
        assert results == [simple_mapping, other_mapping]
