name: "mypy"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Micromamba"
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: gufe
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=3.10
            rdkit=2023.09.5
          init-shell: bash

      - name: "Install steps"
        run: |
          python -m pip install mypy
          python -m pip install --no-deps -e .

      - name: "Environment Information"
        run: |
          micromamba info -a
          micromamba list

      - name: "Lint with mypy"
        run: mypy
